services:
  db:
    image: postgres
    container_name: bankuish_db
    environment:
      POSTGRES_USER: bankuish_user
      POSTGRES_PASSWORD: Bankuish2024
      POSTGRES_DB: bankuish_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: courses-service
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: bankuish_user
      DATABASE_PASSWORD: Bankuish2024
      DATABASE_NAME: bankuish_db
      HTTP_PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - /app/node_modules
volumes:
  postgres-data:
